### ISSUE TITLE
Replace Jackson for JS and native compatibility

### ISSUE THREAD

**Issue by kris7t** [FTSRG/theta-jani-interchange#1]
We should strive for compatibility with Kotlin JavaScript and native backends, so that the library can be used in a browser application as a client communicating with a model checker over WebSocket, as well as in model checkers that take advantage of the fast startup and small memory footprint of native applications.

Our main JVM dependency is currently [Jackson](https://github.com/FasterXML/jackson), of which we use several advanced features. A possibly multiplatform alternative would be [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization), however, it lacks several key features:
* [x] Custom naming for `enum class`es -- probably doable, albeit with writing custom serializer boilerplate
* [ ] Serialization of `object`s as if they were `enum class` literals (in the `Type` JANI schema)
* [ ] Omit default values from serialization, including `null`s and empty collections
* [ ] Polymorphic serialization -- there is some support, but lacking for our use-case
  * [x] Reuse generated momorphic serializer in polymorphic serialization -- supported, but only with a wrapper array, or by casting to `JSON.JsonInput`: https://gist.github.com/tokou/1660906bd103b0a68f2da283a9c6522c
  * [ ] Use polymorphic serializer during polymorphic (de)serialization of another object -- fails, see ef21eb51a89096160dabceca09ebc58fd020063f
  * [ ] Customize type names
  * [ ] Place type name attribute inside the serializer object literal
  * [ ] Map multiple type name values to the same concrete class (for unary and binary operator handling)
  * [ ] Access to the type name attribute from the monomorphic serializer being delegated to (for storing the requested unary and binary operator)
  * [ ] Serializing some child classes as primitive literals instead of objects (for `ConstantExpression` ans `Identifier` expressions)
  * [ ] Multiple possible type name attributes (`op` vs `distribution`)
  * [ ] Dispatching to conrete classes by the attributes present instead of the type name (`NamedExpression`)
  * [ ] Reuse a polymorphic deserializer for descendant interfaces by downcasting (uses of `DowncastSerializer`, e.g., `ConstantType` and `BasicNumericType` should delegate to `Type` and check type conformance afterwards)

Due to this laundry list of features, it may actually make more sense to forego using the _kotlinx.serializer_ compiler plugin, and just write the neccessary (de)serializers by hand, relying on some low level API (something comparable to `JsonParser` in Jackson). However, before going down that route, we should significantly improve unit test coverage to avoid regressions caused by switching to manually written boilerplate...

**Comment by kris7t** [comment]
After discussing on `#serialization` on the kotlinlang slack, it turns out that polymorphic serialization with lookahead is somewhat doable: https://gist.github.com/tokou/1660906bd103b0a68f2da283a9c6522c (Thanks @tokou!)

The problem is _recursive_ polymorphic serialization, i.e., writing polymorphic serializers for objects that are used within fields of polymorphically serialized objects. The failing `TypesTests` in commit ef21eb51a89096160dabceca09ebc58fd020063f illustrate this issue. During polymorphic deserialization, `JSON.JsonInput` is replaced with `JsonTreeMapper.JsonTreeInput`, which does not support `readTree()`. Hence no further polymorphic deserialization is possible. The analogous issue appears in serialization.
